#  Restart the appplication for code updates to take effect 
name: Restart the appplication for code updates to take effect
run-name: ${{ github.actor }} is restarting the application 🚀
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://odfasu.feele.exeter.ac.uk/ctrl/container_restart?accessToken=0e48e941-0c51-4cb9-910a-a081db8f5743'
        method: 'POST'
